#!/bin/bash
################################################################################
# nfs3-loadgen.sh
#
# NFSv3 protocol feature and traffic exerciser for VAST.
# Default target: /mnt/kmacs-root/nfstest
#
# Lights up the RPCs that opstat --nfs --version=3.0 tracks:
#   GETATTR, SETATTR, LOOKUP, ACCESS, READLINK, READ, WRITE,
#   CREATE, MKDIR, SYMLINK, MKNOD, REMOVE, RMDIR, RENAME, LINK,
#   READDIR / READDIRPLUS, FSSTAT, PATHCONF, COMMIT
# plus NLM byte-range locks via lockd (NFSv3 has no OPEN/CLOSE state,
# compounding, or delegations).
#
# FSINFO is sent at mount time. NULL is not generated by the Linux client.
################################################################################

if [ "$EUID" -ne 0 ]; then
  echo "Please run as root (sudo)."
  exit 1
fi

MOUNT_POINT="${1:-/mnt/kmacs-root/nfstest}"
WORKDIR="$MOUNT_POINT/nfs3_loadgen"

is_nfs3_mount() {
  local mp="$1"
  local fstype="" opts="" src=""

  if command -v findmnt >/dev/null 2>&1; then
    fstype=$(findmnt -n -o FSTYPE --target "$mp" 2>/dev/null || true)
    opts=$(findmnt -n -o OPTIONS --target "$mp" 2>/dev/null || true)
    src=$(findmnt -n -o SOURCE --target "$mp" 2>/dev/null || true)
    [ -z "$fstype" ] && return 1
    case "$fstype" in
      nfs3) return 0 ;;
      nfs4|nfs4.*) return 1 ;;
      nfs)
        echo "$opts" | grep -qE '(^|,)(vers|nfsvers)=4' && return 1
        echo "$opts" | grep -qE '(^|,)(vers|nfsvers)=3(,|$)' && return 0
        # Older clients omit vers= and default to NFSv3
        return 0
        ;;
      *) return 1 ;;
    esac
  fi

  src=$(mount | grep " on ${mp} type ")
  echo "$src" | grep -q " type nfs3 " && return 0
  echo "$src" | grep -qE 'vers=3|nfsvers=3' && return 0
  echo "$src" | grep -q " type nfs " && ! echo "$src" | grep -qE 'vers=4|nfsvers=4|type nfs4' && return 0
  return 1
}

if [ ! -d "$MOUNT_POINT" ]; then
  echo "[!] Error: $MOUNT_POINT does not exist."
  exit 1
fi

if ! is_nfs3_mount "$MOUNT_POINT"; then
  echo "[!] Error: $MOUNT_POINT is not active or is not mounted as NFSv3."
  echo "    findmnt: $(findmnt -n --target "$MOUNT_POINT" 2>/dev/null || mount | grep " $MOUNT_POINT " || echo 'not found')"
  exit 1
fi

if ! command -v fio >/dev/null 2>&1; then
  echo "[!] Error: fio is not installed. Install it and re-run."
  exit 1
fi

IOENGINE="libaio"
if fio --enghelp 2>/dev/null | grep -q '^[[:space:]]*io_uring'; then
  IOENGINE="io_uring"
fi

mkdir -p "$WORKDIR" || {
  echo "[!] Error: cannot create $WORKDIR on the NFSv3 mount."
  exit 1
}

echo "======================================================================"
echo " LAUNCHING VAST NFSv3 PROTOCOL FEATURE & TRAFFIC EXERCISER            "
echo "======================================================================"
echo " -> Target Mount: $MOUNT_POINT"
echo " -> Work dir:     $WORKDIR"
echo " -> fio engine:   $IOENGINE"
echo " -> Exercising:   NLM locks, CREATE/MKDIR/LOOKUP/REMOVE/RMDIR,"
echo "                  RENAME/LINK/SYMLINK/MKNOD/READLINK, GETATTR/SETATTR,"
echo "                  ACCESS/FSSTAT/PATHCONF, COMMIT, and parallel I/O"
echo "----------------------------------------------------------------------"
echo " [+] RUNNING FOREVER. Press [Ctrl + C] or: systemctl stop nfs3-loadgen"
echo "======================================================================"

PID_LOCK=""
PID_META=""
PID_ATTR=""
PID_COMMIT=""
PID_FIO=""

cleanup() {
  echo -e "\n\n[!] Caught Ctrl-C! Cleaning up background traffic loops..."

  kill $PID_FIO $PID_META $PID_ATTR $PID_LOCK $PID_COMMIT 2>/dev/null
  wait $PID_FIO $PID_META $PID_ATTR $PID_LOCK $PID_COMMIT 2>/dev/null

  rm -rf "$WORKDIR" 2>/dev/null

  echo "[+] All stress testing loops terminated cleanly. Exiting."
  exit 0
}
trap cleanup INT TERM

# ----------------------------------------------------------------------
# LOOP A: NLM byte-range locking (lockd). NFSv3 has no NFSv4 LOCK ops.
# ----------------------------------------------------------------------
echo "[+] Starting NLM byte-range locking loop..."
touch "$WORKDIR/lock_stress.dat"
while true; do
  (
    flock -x 200
    echo "$(date): Lock Acquired By Process $$" >> "$WORKDIR/lock_stress.dat"
  ) 200>"$WORKDIR/lock_stress.dat"
  sleep 0.1
done >/dev/null 2>&1 &
PID_LOCK=$!

# ----------------------------------------------------------------------
# LOOP B: Namespace churn (CREATE/MKDIR/LOOKUP/REMOVE/RMDIR/RENAME/
#         LINK/SYMLINK/MKNOD/READLINK + READDIRPLUS via ls -lR)
# ----------------------------------------------------------------------
echo "[+] Starting metadata & namespace stress..."
while true; do
  mkdir -p "$WORKDIR/meta_stress"/dir_{1..5}

  for i in {1..40}; do
    touch "$WORKDIR/meta_stress/dir_$((1 + RANDOM % 5))/file_$i"
  done

  # RENAME
  mv "$WORKDIR/meta_stress/dir_1/file_1" "$WORKDIR/meta_stress/dir_1/file_1.renamed" 2>/dev/null

  # LINK (hard) and SYMLINK + READLINK
  ln "$WORKDIR/meta_stress/dir_2/file_2" "$WORKDIR/meta_stress/dir_2/file_2.hard" 2>/dev/null
  ln -s "file_3" "$WORKDIR/meta_stress/dir_3/file_3.sym" 2>/dev/null
  readlink "$WORKDIR/meta_stress/dir_3/file_3.sym" >/dev/null 2>&1

  # MKNOD (fifo; avoids needing device-node privileges)
  mkfifo "$WORKDIR/meta_stress/dir_4/fifo_n" 2>/dev/null || mknod "$WORKDIR/meta_stress/dir_4/fifo_n" p 2>/dev/null

  # LOOKUP + READDIRPLUS (Linux NFSv3 client uses READDIRPLUS unless nordirplus)
  ls -lR "$WORKDIR/meta_stress" >/dev/null 2>&1

  rm -rf "$WORKDIR/meta_stress"
  sleep 0.2
done >/dev/null 2>&1 &
PID_META=$!

# ----------------------------------------------------------------------
# LOOP C: GETATTR / SETATTR / ACCESS / FSSTAT / PATHCONF
# ----------------------------------------------------------------------
echo "[+] Starting NFSv3 attribute, access, and FSSTAT loop..."
touch "$WORKDIR/attr_stress.txt"
while true; do
  chmod 777 "$WORKDIR/attr_stress.txt"
  chown nobody:nogroup "$WORKDIR/attr_stress.txt" 2>/dev/null \
    || chown nobody:nobody "$WORKDIR/attr_stress.txt" 2>/dev/null
  chmod 600 "$WORKDIR/attr_stress.txt"
  touch -d "now" "$WORKDIR/attr_stress.txt" 2>/dev/null
  stat "$WORKDIR/attr_stress.txt" >/dev/null 2>&1
  test -r "$WORKDIR/attr_stress.txt"
  test -w "$WORKDIR/attr_stress.txt"
  test -x "$WORKDIR/attr_stress.txt"
  df -h "$MOUNT_POINT" >/dev/null 2>&1
  stat -f "$MOUNT_POINT" >/dev/null 2>&1 || stat -c '%s' "$MOUNT_POINT" >/dev/null 2>&1
  getconf NAME_MAX "$MOUNT_POINT" >/dev/null 2>&1
  getconf PATH_MAX "$MOUNT_POINT" >/dev/null 2>&1
  sleep 0.1
done >/dev/null 2>&1 &
PID_ATTR=$!

# ----------------------------------------------------------------------
# LOOP D: COMMIT via O_DSYNC writes + fsync
# ----------------------------------------------------------------------
echo "[+] Starting COMMIT (dsync/fsync) loop..."
dd if=/dev/zero of="$WORKDIR/commit.dat" bs=1M count=8 status=none 2>/dev/null
while true; do
  dd if=/dev/urandom of="$WORKDIR/commit.dat" bs=64k count=16 conv=notrunc oflag=dsync status=none 2>/dev/null
  sync "$WORKDIR/commit.dat" 2>/dev/null || true
  sleep 0.2
done >/dev/null 2>&1 &
PID_COMMIT=$!

# ----------------------------------------------------------------------
# LOOP E: Core FIO parallel I/O (READ / WRITE; NLM posix locks)
# ----------------------------------------------------------------------
echo "[+] Spawning core FIO high-concurrency engine (NLM file locks)..."
while true; do
  fio --time_based --runtime=60 --ioengine="$IOENGINE" --direct=1 --group_reporting=0 \
    --directory="$WORKDIR" \
    --name=nfs3_nlm_locks --filename=fio_locks.bin --rw=randrw --bs=4k --iodepth=16 --numjobs=4 --size=1g --lockfile=exclusive \
    --name=nfs3_heavy_iops --filename=fio_iops.bin --rw=randrw --rwmixread=70 --bs=4k --iodepth=64 --numjobs=4 --size=2g \
    --name=nfs3_seq_bw --filename=fio_bw.bin --rw=read --bs=1m --iodepth=16 --numjobs=2 --size=4g \
    --name=nfs3_commit --filename=fio_commit.bin --rw=write --bs=64k --iodepth=8 --numjobs=2 --size=1g --fsync=16 \
    >/dev/null 2>&1
  sleep 1
done &
PID_FIO=$!

echo "----------------------------------------------------------------------"
echo " ALL WORKLOADS ACTIVE. Terminal output quieted to protect dashboard lookups."
echo " Fire up './opstat --nfs --version=3.0' and watch the metrics fly!"
echo "----------------------------------------------------------------------"

while true; do
  sleep 1
done
